framework:
    cache:

      default_redis_provider: redis://%env(REDIS_HOST)%:%env(int:REDIS_PORT)%
      pools:

        game_cache_pool:
          #adapter: cache.adapter.filesystem
          adapter: cache.adapter.redis
          tags: true
