doctrine:
    dbal:
        default_connection: default
        # Enable savepoints for nested transactions
        connections:
            default:
                schema_filter: '~^(?!messenger_messages)~'
                dbname:         '%env(resolve:DATABASE_DBNAME)%'
                host:           '%env(resolve:DATABASE_HOST)%'
                port:           '%env(resolve:DATABASE_PORT)%'
                user:           '%env(resolve:DATABASE_USER)%'
                password:       '%env(resolve:DATABASE_PASSWORD)%'
                driver:         '%env(resolve:DATABASE_DRIVER)%'
                server_version: '%env(resolve:DATABASE_VERSION)%'
                use_savepoints: true
                profiling_collect_backtrace: '%kernel.debug%'

            queue:
                schema_filter: '~^(?!messenger_messages)~'
                dbname:         '%env(resolve:DATABASE_DBNAME)%'
                host:           '%env(resolve:DATABASE_HOST)%'
                port:           '%env(resolve:DATABASE_PORT)%'
                user:           '%env(resolve:DATABASE_USER)%'
                password:       '%env(resolve:DATABASE_PASSWORD)%'
                driver:         '%env(resolve:DATABASE_DRIVER)%'
                server_version: '%env(resolve:DATABASE_VERSION)%'
                use_savepoints: true
                profiling_collect_backtrace: '%kernel.debug%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        quote_strategy: doctrine.orm.quote_strategy.default
        auto_mapping: true
        dql:
          string_functions:
            JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
