framework:
    default_locale: de
    translator:
        paths:
          - '%kernel.project_dir%/translations'
          - '%kernel.project_dir%/packages/myhordes-fixtures/src/content/translations'
        fallbacks:
          - en
          - de
        logging: false
        providers:
            crowdin:
                dsn: '%env(CROWDIN_DSN)%'
                locales:
                  - en
                  - fr
                  - es
                  - de
