# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/PHP.gitlab-ci.yml

image: registry.gitlab.com/eternaltwin/myhordes/myhordes-registry:latest

# Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ee/ci/services/README.html for examples.
default:
  services:
    - name: mariadb:latest
      alias: mariadb

# Set any variables we need
variables:
  # MariaDB environments variables
  MARIADB_DATABASE: myhordes
  MARIADB_USER: myhordes-ci
  MARIADB_PASSWORD: Sullen.Vindicate9.Untruth
  MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
  MARIADB_ROOT_PASSWORD: Unbolted5-Overgrown2-Outscore2-Yodel1

  # MH environment variables
  DATABASE_URL: mysql://myhordes-ci:Sullen.Vindicate9.Untruth@mariadb:3306/myhordes?serverVersion=11.2.2-MariaDB
  DATABASE_DBNAME: myhordes
  DATABASE_HOST: mariadb
  DATABASE_PORT: 3306
  DATABASE_USER: myhordes-ci
  DATABASE_PASSWORD: Sullen.Vindicate9.Untruth
  DATABASE_DRIVER: pdo_mysql
  DATABASE_VERSION: 11.2.2-MariaDB
  XDEBUG_MODE: coverage

stages:
  - build
  - test-translate
  - deploy

build:
  stage: build
  script:
    # Run Composer
    - composer require myhordes/prime:3.0.0
    - composer install
    # Install assets
    - yarn install
    - yarn encore dev
    # Install default DB
    # - php bin/console app:migrate -i -vvv
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - vendor
      - node_modules
      - public/build
      - templates/build
  rules:
    - changes:
        - composer.json
        - package.json
        - composer.lock
        - yarn.lock
        - assets/**/*
        - .gitlab-ci.yml

translate:
  stage: test-translate
  dependencies:
    - build
  script:
    # Install a DB
    - php bin/console app:migrate -i -vvv --skip-optional
    # Let's generate source strings
    - bin/console app:translation:update de
    # And we send it to Crowdin
    - crowdin upload sources -b translation-main
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - vendor
      - node_modules
      - public/build
      - templates/build
  rules:
    - if: $CI_PIPELINE_SOURCE != "push"
      when: never
    - if: $CI_COMMIT_TAG =~ /^translate-\d+/
      when: on_success
  variables:
    CROWDIN_API_TOKEN: $CROWDIN_API_TOKEN
    CROWDIN_PROJECT_ID: $CROWDIN_PROJECT_ID
    APP_ENV: translation

translate-next:
  stage: test-translate
  dependencies:
    - build
  script:
    # Install a DB
    - php bin/console app:migrate -i -vvv --skip-optional
    # Let's generate source strings
    - bin/console app:translation:update de
    # And we send it to Crowdin
    - crowdin upload sources -b translation-main-next
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - vendor
      - node_modules
      - public/build
      - templates/build
  rules:
    - if: $CI_PIPELINE_SOURCE != "push"
      when: never
    - if: $CI_COMMIT_TAG =~ /^translate-next-\d+/
      when: on_success
  variables:
    CROWDIN_API_TOKEN: $CROWDIN_API_TOKEN
    CROWDIN_PROJECT_ID: $CROWDIN_PROJECT_ID
    APP_ENV: translation_next

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:
  stage: test-translate
  dependencies:
    - build
  script:
    # build cache
    - php bin/console cache:warmup --env=dev
    # run phpstan
    - vendor/bin/phpstan analyse --no-progress --error-format=gitlab > phpstan.json
    - export APP_ENV=test
    - echo $DATABASE_URL
    # Install a DB
    - php bin/console app:migrate -i -vvv
    # Run tests
    - vendor/bin/phpunit # --coverage-text --colors=never
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - vendor
      - node_modules
      - public/build
      - templates/build
  except:
    refs:
      - /^l10n_.*/
  artifacts:
    when: always
    reports:
      codequality: phpstan.json

deploy_staging:
  stage: deploy
  dependencies:
    - test
  script:
    - apt-get update -yqq
    - apt-get install -yqq sshpass
    - export SSHPASS=$SSH_PASSWORD
    - sshpass -e ssh -p 12002 -o stricthostkeychecking=no deployer@newhope.aifesdespets.fr 'cd /var/www/chehtan.dev/myhordes/www && bin/console app:migrate -g --remote origin --branch master --environment dev --phar --release'
    - unset SSHPASS
  only:
    - master
  environment:
    name: ludo-staging
    url: https://myhordes.chehtan.dev