"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_TOKEN"
files:
  - source: /translations/*.de.yml
    translation: /translations/%file_name%.%two_letters_code%.yml
    translation_replace:
      .de: ''
