"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_TOKEN"
"base_path": "./"
"preserve_hierarchy": true
"base_url": "https://api.crowdin.com"         # https://{organization-name}.crowdin.com for Crowdin Enterprise

files:
  - source: /translations/*.de.yml
    translation: /translations/%file_name%.%two_letters_code%.yml
    translation_replace:
      .de: ''
