controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auto_logout:
  path: /logout
  methods: GET

prime:
  resource: '@MyHordesPrimeBundle/Resources/config/routing.yaml'