parameters:
  local: []
  myhordes:
    nightly:
      retries: 3
      date_modifier: "tomorrow"
    backup:
      path: ~
      compression: ~
      limits:
        nightly: 0
        daily: 7
        weekly: 4
        monthly: 12
        update: 2
        manual: -1
    coalitions:
      size: 5
    anti-grief:
      min-sp: 20
      reg-limit: 2
    fatalmail:
      target: ~
      source: ~
    domains: []
    twinoid:
      sk: ~
      id: ~
      domain: ~
    etwin:
      reg: ~
      auth: ~
      api: ~
      sk: ~
      return: ~
      app: myhordes@clients
      dual-stack: true
    soulpoints:
      limits:
        remote: 100
        panda: 500
        return_small: 500
        custom: 1000
    towns:
      autolangs: ['de','en','fr','es']
      openmin:
        remote: 1
        panda: 1
        small: 1
        custom: 0
    soul_import:
      enabled: true
      readonly: false
      limited: false
      sp_threshold: 15
    avatars:
      allow_raw: false
      max_processing_size: 3145728 # 3MB
      max_storage_size: 1048576 # 1MB