parameters:
  local: []
  myhordes:
    coalitions:
      size: 5
    anti-grief:
      min-sp: 20
      reg-limit: 2
    fatalmail:
      target: ~
      source: ~
    twinoid:
      sk: ~
      id: ~
    etwin:
      auth: ~
      api: ~
      sk: ~
      app: myhordes
      dual-stack: true
    allow_raw_avatars: false
    soulpoints:
      limits:
        remote: 0 # 100
        panda: 0 # 500
        return_small: 0 # 500
        custom: 0 # 1000
    towns:
      openmin:
        remote: 1
        panda: 0
        small: 1
        custom: 0