parameters:
  base_uri: https://myhordes.de
  local: []
  myhordes:
    nightly:
      retries: 3
      date_modifier: "tomorrow"
    backup:
      path: ~ # Working directory
      compression: ~
      limits:
        nightly: 0
        daily: 7
        weekly: 4
        monthly: 12
        update: 2
        manual: -1
      storages:
        local:
          enabled: true
          type: 'local'
          path: '~/var/backup'
        remote:
          enabled: false
          type: 'ftp'
          host: 'ftp.example.com'
          port: 21
          user: 'ftpuser'
          pass: 'ftppass'
          path: '/'
          passive: true
        sftpremote:
          enabled: false
          type: 'sftp'
          host: 'sftp.example.com'
          port: 22
          user: 'sftpuser'
          pass: 'sftppass'
          path: '/'

    coalitions:
      size: 5
      inactive_after_days: 5
    anti-grief:
      min-sp: 20
      reg-limit: 2
      foreign-cap: 0
    animail:
      discord: ~
    modmail:
      discord: ~
    fatalmail:
      target: ~
      source: ~
      discord: ~
    domains: []
    urls: []
    issue_tracking:
      fallback-url: 'https://gitlab.com/eternaltwin/myhordes/myhordes/-/issues'
      gitlab:
        token: ~
        project-id: ~
    twinoid:
      sk: ~
      id: ~
      domain: ~
    etwin:
      reg: ~
      auth: ~
      internal: ~
      api: ~
      sk: ~
      return: ~
      app: myhordes@clients
      dual-stack: true
    soulpoints:
      limits:
        remote: 0
        panda: 200
        return_small: 0
        custom: 1000
    langs:
      - code: fr
        label: Französisch
        tooltip: ''
        generate: true
      - code: en
        label: Englisch
        tooltip: ''
        generate: true
      - code: de
        label: Deutsch
        tooltip: ''
        generate: true
      - code: es
        label: Spanisch
        tooltip: ''
        generate: true
      - code: ach
        label: 'im-Kontext Übersetzung'
        tooltip: 'Mit dieser speziellen Sprache aktivierst du die Crowdin-Kontextübersetzung. Damit kannst du MyHordes direkt aus dem Spiel heraus übersetzen.'
        generate: false
    towns:
      max_private: 10
      autolangs: ['de','en','fr','es']
      openmin:
        remote: 1
        panda: 1
        small: 1
        custom: 0
    soul_import:
      enabled: true
      readonly: false
      limited: true
      sp_threshold: 15
      tw_threshold: 5
      tw_cutoff: 1635199200
    mail:
      slice_domain: 0 # 0 = use active server domain as mail domain; 2 = scrap any sub domains
    registration:
      token_only: false
    avatars:
      allow_raw: false
      max_processing_size: 3145728 # 3MB
      max_storage_size: 1048576 # 1MB
    staging:
      enabled: false
      prototown:
        enabled: true
        days: 45
      herodays: 1000
      features: ['f_wtns','f_arma','f_cam','f_alarm','f_share']
    override:
      version: ~
      blackboard: ~
      autopost_addendum:
        1: ~
        2: ~
        3: ~
        4: ~