parameters:
  myhordes:
    soulpoints:
      limits:
        remote: 0 # 100
        panda: 0 # 500
        return_small: 0 # 500
        custom: 0 # 1000
    towns:
      openmin:
        remote: 4
        panda: 2
        small: 2
        custom: 0