parameters:
  local: []
  myhordes:
    coalitions:
      size: 5
    fatalmail:
      target: ~
      source: ~
    twinoid:
      sk: ~
      id: ~
    allow_raw_avatars: false
    soulpoints:
      limits:
        remote: 0 # 100
        panda: 0 # 500
        return_small: 0 # 500
        custom: 0 # 1000
    towns:
      openmin:
        remote: 1
        panda: 0
        small: 1
        custom: 0