# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    MyHordes\Prime\EventListener\:
      resource: '../src/templates/EventListener'
    MyHordes\Prime\Controller\:
      resource: '../src/Controller'
    MyHordes\Prime\Helpers\:
      resource: '../src/templates/Helpers'

    MyHordes\Prime\Service\ActionDataService:
      tags: [ { name: 'myhordes.fixtures.actions', priority: 1 } ]
    MyHordes\Prime\Service\AwardTitleDataService:
      tags: [ { name: 'myhordes.fixtures.awards.titles', priority: 1 } ]

    MyHordes\Prime\Service\CitizenHomeLevelDataService:
      tags: [ { name: 'myhordes.fixtures.citizen.home.levels', priority: 1 } ]
    MyHordes\Prime\Service\CitizenProfessionDataService:
      tags: [ { name: 'myhordes.fixtures.citizen.professions', priority: 1 } ]
    MyHordes\Prime\Service\CitizenStatusDataService:
      tags: [ { name: 'myhordes.fixtures.citizen.status', priority: 1 } ]

    MyHordes\Prime\Service\HeroSkillDataService:
      tags: [ { name: 'myhordes.fixtures.heroskills', priority: 1 } ]

    MyHordes\Prime\Service\ItemDataService:
      tags: [ { name: 'myhordes.fixtures.items.list', priority: 1 } ]
    MyHordes\Prime\Service\ItemPropertyDataService:
      tags: [ { name: 'myhordes.fixtures.items.properties', priority: 1 } ]

    MyHordes\Prime\Service\BuildingDataService:
      tags: [ { name: 'myhordes.fixtures.buildings', priority: 1 } ]
      
    MyHordes\Prime\Service\RuinDataService:
      tags: [ { name: 'myhordes.fixtures.ruins.data', priority: 1 } ]

    MyHordes\Prime\Service\RecipeDataService:
      tags: [ { name: 'myhordes.fixtures.recipes', priority: 1 } ]

    MyHordes\Prime\Service\HookDataService:
      tags: [ { name: 'myhordes.fixtures.hooks', priority: 1 } ]

    MyHordes\Prime\Service\LogsDataService:
      tags: [ { name: 'myhordes.fixtures.logs', priority: 1 } ]

    MyHordes\Prime\Service\PictoDataService:
      tags: [ { name: 'myhordes.fixtures.pictos', priority: 1 } ]

    MyHordes\Prime\Service\ItemGroupDataService:
      tags: [ { name: 'myhordes.fixtures.items.groups', priority: 1 } ]

    MyHordes\Prime\Configuration\Events\ChristmasEventOverride:
      tags: [ { name: 'myhordes.configuration.events', priority: 1 } ]