<?php

namespace MyHordes\Fixtures\Service;

use MyHordes\Fixtures\DTO\Awards\AwardTitlePrototypeDataContainer;
use MyHordes\Plugins\Interfaces\FixtureProcessorInterface;

class AwardTitleDataService implements FixtureProcessorInterface {

    public function process(array &$data): void
    {
        $container = new AwardTitlePrototypeDataContainer($data);

        $container->add()->title('Pfadfinder')->unlockquantity(10)->associatedtag(':proscout:')->associatedpicto('r_jrangr_#00')->commit();
        $container->add()->title('Ninja')->unlockquantity(25)->associatedtag(':proscout:')->associatedpicto('r_jrangr_#00')->commit();
        $container->add()->title('Green Beret')->unlockquantity(75)->associatedtag(':proscout:')->associatedpicto('r_jrangr_#00')->commit();
        $container->add()->title('Schattenmann')->unlockquantity(150)->associatedtag(':proscout:')->associatedpicto('r_jrangr_#00')->commit();
        $container->add()->title('Wüstenphantom')->unlockquantity(300)->associatedtag(':proscout:')->associatedpicto('r_jrangr_#00')->commit();
        $container->add()->title('Solid Snake war gestern...')->unlockquantity(800)->associatedtag(':proscout:')->associatedpicto('r_jrangr_#00')->commit();
        $container->add()->title('Der unsichtbare Mann')->unlockquantity(1500)->associatedtag(':proscout:')->associatedpicto('r_jrangr_#00')->commit();
        $container->add()->title('Sandarbeiter')->unlockquantity(10)->associatedtag(':proscav:')->associatedpicto('r_jcolle_#00')->commit();
        $container->add()->title('Wüstenspringmaus')->unlockquantity(25)->associatedtag(':proscav:')->associatedpicto('r_jcolle_#00')->commit();
        $container->add()->title('Großer Ameisenbär')->unlockquantity(75)->associatedtag(':proscav:')->associatedpicto('r_jcolle_#00')->commit();
        $container->add()->title('Wüstenfuchs')->unlockquantity(150)->associatedtag(':proscav:')->associatedpicto('r_jcolle_#00')->commit();
        $container->add()->title('Ich sehe Alles!')->unlockquantity(300)->associatedtag(':proscav:')->associatedpicto('r_jcolle_#00')->commit();
        $container->add()->title('Ein BMW? Kein Problem!')->unlockquantity(800)->associatedtag(':proscav:')->associatedpicto('r_jcolle_#00')->commit();
        $container->add()->title('Où est Larchi ?')->unlockquantity(1500)->associatedtag(':proscav:')->associatedpicto('r_jcolle_#00')->commit();
        $container->add()->title('Tierliebhaber')->unlockquantity(10)->associatedtag(':protamer:')->associatedpicto('r_jtamer_#00')->commit();
        $container->add()->title('Malteserzüchter')->unlockquantity(25)->associatedtag(':protamer:')->associatedpicto('r_jtamer_#00')->commit();
        $container->add()->title('Ich bändige Bestien')->unlockquantity(75)->associatedtag(':protamer:')->associatedpicto('r_jtamer_#00')->commit();
        $container->add()->title('Nie ohne meinen Hund!')->unlockquantity(150)->associatedtag(':protamer:')->associatedpicto('r_jtamer_#00')->commit();
        $container->add()->title('Hundewurst schmeckt gar nicht schlecht!')->unlockquantity(300)->associatedtag(':protamer:')->associatedpicto('r_jtamer_#00')->commit();
        $container->add()->title('Meser (halb Mensch, halb Malteser)')->unlockquantity(800)->associatedtag(':protamer:')->associatedpicto('r_jtamer_#00')->commit();
        $container->add()->title('Personalisierter Titel - Dompteur (T-ID: 1725642)')->unlockquantity(1500)->associatedtag(':protamer:')->associatedpicto('r_jtamer_#00')->commit();
        $container->add()->title('Wurmfresser')->unlockquantity(10)->associatedtag(':prosurv:')->associatedpicto('r_jermit_#00')->commit();
        $container->add()->title('Meister im Würmerfinden')->unlockquantity(25)->associatedtag(':prosurv:')->associatedpicto('r_jermit_#00')->commit();
        $container->add()->title('Gefräßiger Bürger')->unlockquantity(75)->associatedtag(':prosurv:')->associatedpicto('r_jermit_#00')->commit();
        $container->add()->title('Wüstenwurmzüchter')->unlockquantity(150)->associatedtag(':prosurv:')->associatedpicto('r_jermit_#00')->commit();
        $container->add()->title('Ich brauche niemanden!')->unlockquantity(300)->associatedtag(':prosurv:')->associatedpicto('r_jermit_#00')->commit();
        $container->add()->title('Heraklit der Außenwelt')->unlockquantity(800)->associatedtag(':prosurv:')->associatedpicto('r_jermit_#00')->commit();
        $container->add()->title('Gepanzerter Fakir')->unlockquantity(1500)->associatedtag(':prosurv:')->associatedpicto('r_jermit_#00')->commit();
        $container->add()->title('Diplomierter Scharlatan')->unlockquantity(10)->associatedtag(':prosham:')->associatedpicto('r_jsham_#00')->commit();
        $container->add()->title('Schlimmer Finger')->unlockquantity(25)->associatedtag(':prosham:')->associatedpicto('r_jsham_#00')->commit();
        $container->add()->title('Seelenverwerter')->unlockquantity(75)->associatedtag(':prosham:')->associatedpicto('r_jsham_#00')->commit();
        $container->add()->title('Mystischer Seher')->unlockquantity(150)->associatedtag(':prosham:')->associatedpicto('r_jsham_#00')->commit();
        $container->add()->title('Voodoo Sorceror')->unlockquantity(300)->associatedtag(':prosham:')->associatedpicto('r_jsham_#00')->commit();
        $container->add()->title('Allwissender Schamane')->unlockquantity(800)->associatedtag(':prosham:')->associatedpicto('r_jsham_#00')->commit();
        $container->add()->title('Anführer der verlorenen Seelen')->unlockquantity(1500)->associatedtag(':prosham:')->associatedpicto('r_jsham_#00')->commit();
        $container->add()->title('Yo, wir schaffen das!')->unlockquantity(10)->associatedtag(':protech:')->associatedpicto('r_jtech_#00')->commit();
        $container->add()->title('Kleiner Schraubendreher')->unlockquantity(25)->associatedtag(':protech:')->associatedpicto('r_jtech_#00')->commit();
        $container->add()->title('Schweizer Taschenmesser')->unlockquantity(75)->associatedtag(':protech:')->associatedpicto('r_jtech_#00')->commit();
        $container->add()->title('Unermüdlicher Schrauber')->unlockquantity(150)->associatedtag(':protech:')->associatedpicto('r_jtech_#00')->commit();
        $container->add()->title('Seele des Handwerks')->unlockquantity(300)->associatedtag(':protech:')->associatedpicto('r_jtech_#00')->commit();
        $container->add()->title('Seele eines Profis')->unlockquantity(800)->associatedtag(':protech:')->associatedpicto('r_jtech_#00')->commit();
        $container->add()->title('Personalisierter Titel - Techniker (T-ID: 631944)')->unlockquantity(1500)->associatedtag(':protech:')->associatedpicto('r_jtech_#00')->commit();
        $container->add()->title('Die Mauer')->unlockquantity(10)->associatedtag(':proguard:')->associatedpicto('r_jguard_#00')->commit();
        $container->add()->title('Höllenwächter')->unlockquantity(25)->associatedtag(':proguard:')->associatedpicto('r_jguard_#00')->commit();
        $container->add()->title('Kerberos')->unlockquantity(75)->associatedtag(':proguard:')->associatedpicto('r_jguard_#00')->commit();
        $container->add()->title('Die letzte Verteidigungslinie')->unlockquantity(150)->associatedtag(':proguard:')->associatedpicto('r_jguard_#00')->commit();
        $container->add()->title('Du kommst hier NICHT durch!')->unlockquantity(300)->associatedtag(':proguard:')->associatedpicto('r_jguard_#00')->commit();
        $container->add()->title('Hekatoncheir')->unlockquantity(800)->associatedtag(':proguard:')->associatedpicto('r_jguard_#00')->commit();
        $container->add()->title('Holy F***ing Iceberg')->unlockquantity(1500)->associatedtag(':proguard:')->associatedpicto('r_jguard_#00')->commit();
        $container->add()->title('Kantinenkoch')->unlockquantity(10)->associatedtag(':tasty:')->associatedpicto('r_cookr_#00')->commit();
        $container->add()->title('Kleiner Küchenchef')->unlockquantity(25)->associatedtag(':tasty:')->associatedpicto('r_cookr_#00')->commit();
        $container->add()->title('Meister Eintopf')->unlockquantity(50)->associatedtag(':tasty:')->associatedpicto('r_cookr_#00')->commit();
        $container->add()->title('Großer Wüstenkonditor')->unlockquantity(100)->associatedtag(':tasty:')->associatedpicto('r_cookr_#00')->commit();
        $container->add()->title('Begnadeter Wüstenkonditor')->unlockquantity(250)->associatedtag(':tasty:')->associatedpicto('r_cookr_#00')->commit();
        $container->add()->title('Cooking Mama')->unlockquantity(500)->associatedtag(':tasty:')->associatedpicto('r_cookr_#00')->commit();
        $container->add()->title('Meisterhafter Kochlöffelschwinger')->unlockquantity(1000)->associatedtag(':tasty:')->associatedpicto('r_cookr_#00')->commit();
        $container->add()->title('Meisterkoch der Sterne')->unlockquantity(2000)->associatedtag(':tasty:')->associatedpicto('r_cookr_#00')->commit();
        $container->add()->title('Amateur-Laborratte')->unlockquantity(10)->associatedtag(':lab:')->associatedpicto('r_drgmkr_#00')->commit();
        $container->add()->title('Kleiner Präparator')->unlockquantity(25)->associatedtag(':lab:')->associatedpicto('r_drgmkr_#00')->commit();
        $container->add()->title('Chemiker von um die Ecke')->unlockquantity(50)->associatedtag(':lab:')->associatedpicto('r_drgmkr_#00')->commit();
        $container->add()->title('Produkttester')->unlockquantity(100)->associatedtag(':lab:')->associatedpicto('r_drgmkr_#00')->commit();
        $container->add()->title('Wüstenstadt-Dealer')->unlockquantity(250)->associatedtag(':lab:')->associatedpicto('r_drgmkr_#00')->commit();
        $container->add()->title('Ich koste alle meine Produkte')->unlockquantity(500)->associatedtag(':lab:')->associatedpicto('r_drgmkr_#00')->commit();
        $container->add()->title('Rauchts? Dann ist es meins.')->unlockquantity(1000)->associatedtag(':lab:')->associatedpicto('r_drgmkr_#00')->commit();
        $container->add()->title('Offizieller AP-Versorger')->unlockquantity(2000)->associatedtag(':lab:')->associatedpicto('r_drgmkr_#00')->commit();
        $container->add()->title('X-Men Leser')->unlockquantity(15)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Aussergewöhnlicher Bürger')->unlockquantity(30)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Wunder')->unlockquantity(50)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Werdender Superheld')->unlockquantity(70)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Volksheld')->unlockquantity(90)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Neo')->unlockquantity(120)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Erlöser der Menschheit')->unlockquantity(150)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Außenweltlegende')->unlockquantity(200)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Messie der verlorenen Welt')->unlockquantity(500)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Mein Name ist Nobody')->unlockquantity(850)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Ein Sternbild trägt meinen Namen')->unlockquantity(1000)->associatedtag(':hero:')->associatedpicto('r_heroac_#00')->commit();
        $container->add()->title('Abstauber')->unlockquantity(20)->associatedtag(':trash:')->associatedpicto('r_solban_#00')->commit();
        $container->add()->title('Müllkind')->unlockquantity(100)->associatedtag(':trash:')->associatedpicto('r_solban_#00')->commit();
        $container->add()->title('Autonomer Müll')->unlockquantity(200)->associatedtag(':trash:')->associatedpicto('r_solban_#00')->commit();
        $container->add()->title('Freier Bürger')->unlockquantity(300)->associatedtag(':trash:')->associatedpicto('r_solban_#00')->commit();
        $container->add()->title('Alles für meinen Mund')->unlockquantity(400)->associatedtag(':trash:')->associatedpicto('r_solban_#00')->commit();
        $container->add()->title('Ich brauche niemanden')->unlockquantity(550)->associatedtag(':trash:')->associatedpicto('r_solban_#00')->commit();
        $container->add()->title('Unabhängiger Großeinsiedler')->unlockquantity(700)->associatedtag(':trash:')->associatedpicto('r_solban_#00')->commit();
        $container->add()->title('Che Guevara der Wüste')->unlockquantity(1000)->associatedtag(':trash:')->associatedpicto('r_solban_#00')->commit();
        $container->add()->title('Maulheld')->unlockquantity(10)->associatedtag(':thief:')->associatedpicto('r_theft_#00')->commit();
        $container->add()->title('Lump')->unlockquantity(30)->associatedtag(':thief:')->associatedpicto('r_theft_#00')->commit();
        $container->add()->title('Schaumschläger')->unlockquantity(40)->associatedtag(':thief:')->associatedpicto('r_theft_#00')->commit();
        $container->add()->title('Dieb')->unlockquantity(50)->associatedtag(':thief:')->associatedpicto('r_theft_#00')->commit();
        $container->add()->title('Fantomas')->unlockquantity(75)->associatedtag(':thief:')->associatedpicto('r_theft_#00')->commit();
        $container->add()->title('Ali Baba')->unlockquantity(100)->associatedtag(':thief:')->associatedpicto('r_theft_#00')->commit();
        $container->add()->title('Meisterdieb')->unlockquantity(500)->associatedtag(':thief:')->associatedpicto('r_theft_#00')->commit();
        $container->add()->title('Kleptomane')->unlockquantity(1000)->associatedtag(':thief:')->associatedpicto('r_theft_#00')->commit();
        $container->add()->title('Dein Haus ist mein Haus')->unlockquantity(2000)->associatedtag(':thief:')->associatedpicto('r_theft_#00')->commit();
        $container->add()->title('Ästhet')->unlockquantity(100)->associatedtag(':deco:')->associatedpicto('r_deco_#00')->commit();
        $container->add()->title('Schaufenstergestalter')->unlockquantity(250)->associatedtag(':deco:')->associatedpicto('r_deco_#00')->commit();
        $container->add()->title('Innenarchitekt')->unlockquantity(500)->associatedtag(':deco:')->associatedpicto('r_deco_#00')->commit();
        $container->add()->title('Möbelgourmet')->unlockquantity(1000)->associatedtag(':deco:')->associatedpicto('r_deco_#00')->commit();
        $container->add()->title('Ordnung muss sein!')->unlockquantity(1500)->associatedtag(':deco:')->associatedpicto('r_deco_#00')->commit();
        $container->add()->title('Ein schöneres Leben')->unlockquantity(2000)->associatedtag(':deco:')->associatedpicto('r_deco_#00')->commit();
        $container->add()->title('Großer E-KEA Katalog')->unlockquantity(2500)->associatedtag(':deco:')->associatedpicto('r_deco_#00')->commit();
        $container->add()->title('Plünderer')->unlockquantity(30)->associatedtag(':pillage:')->associatedpicto('r_plundr_#00')->commit();
        $container->add()->title('Aasgeier')->unlockquantity(60)->associatedtag(':pillage:')->associatedpicto('r_plundr_#00')->commit();
        $container->add()->title('Hyäne')->unlockquantity(100)->associatedtag(':pillage:')->associatedpicto('r_plundr_#00')->commit();
        $container->add()->title('Wegelagerer post mortem')->unlockquantity(200)->associatedtag(':pillage:')->associatedpicto('r_plundr_#00')->commit();
        $container->add()->title('Hungriger Schakal')->unlockquantity(400)->associatedtag(':pillage:')->associatedpicto('r_plundr_#00')->commit();
        $container->add()->title('Kojote der kargen Steppen')->unlockquantity(600)->associatedtag(':pillage:')->associatedpicto('r_plundr_#00')->commit();
        $container->add()->title('Fingerschmied')->unlockquantity(1000)->associatedtag(':pillage:')->associatedpicto('r_plundr_#00')->commit();
        $container->add()->title('Nein, das Ding fasse ich nicht an.')->unlockquantity(50)->associatedtag(':shower:')->associatedpicto('r_cwater_#00')->commit();
        $container->add()->title('Leichenhygieniker')->unlockquantity(100)->associatedtag(':shower:')->associatedpicto('r_cwater_#00')->commit();
        $container->add()->title('Ich liebe den Geruch von gewaschenen Leichen am Morgen.')->unlockquantity(200)->associatedtag(':shower:')->associatedpicto('r_cwater_#00')->commit();
        $container->add()->title('Müllmann')->unlockquantity(60)->associatedtag(':drag:')->associatedpicto('r_cgarb_#00')->commit();
        $container->add()->title('Erfahrener Müllmann')->unlockquantity(100)->associatedtag(':drag:')->associatedpicto('r_cgarb_#00')->commit();
        $container->add()->title('Entsorgungsfachmann')->unlockquantity(200)->associatedtag(':drag:')->associatedpicto('r_cgarb_#00')->commit();
        $container->add()->title('Maccabees-Vertreiber')->unlockquantity(300)->associatedtag(':drag:')->associatedpicto('r_cgarb_#00')->commit();
        $container->add()->title('SM Anhänger')->unlockquantity(20)->associatedtag(':maso:')->associatedpicto('r_maso_#00')->commit();
        $container->add()->title('SM Spezialist')->unlockquantity(40)->associatedtag(':maso:')->associatedpicto('r_maso_#00')->commit();
        $container->add()->title('Nenn mich Herrin')->unlockquantity(60)->associatedtag(':maso:')->associatedpicto('r_maso_#00')->commit();
        $container->add()->title('Ich möchte dein Objekt sein.')->unlockquantity(100)->associatedtag(':maso:')->associatedpicto('r_maso_#00')->commit();
        $container->add()->title('Stadtmetzger')->unlockquantity(30)->associatedtag(':butcher:')->associatedpicto('r_animal_#00')->commit();
        $container->add()->title('Spezialität: Hundesteaks')->unlockquantity(60)->associatedtag(':butcher:')->associatedpicto('r_animal_#00')->commit();
        $container->add()->title('Miezi? Jaaaa, komm her...')->unlockquantity(150)->associatedtag(':butcher:')->associatedpicto('r_animal_#00')->commit();
        $container->add()->title('Fleisch ist mein Gemüse')->unlockquantity(300)->associatedtag(':butcher:')->associatedpicto('r_animal_#00')->commit();
        # $container->add()->title('Nervensäge')->unlockquantity(10)->associatedtag(':ban:')->associatedpicto('r_ban_#00')->commit(); #
        # $container->add()->title('Sozialschmarotzer')->unlockquantity(20)->associatedtag(':ban:')->associatedpicto('r_ban_#00')->commit(); #
        # $container->add()->title('Die Wüste ist mein Zuhause')->unlockquantity(30)->associatedtag(':ban:')->associatedpicto('r_ban_#00')->commit(); #
        $container->add()->title('Immer ein Auge offen')->unlockquantity(20)->associatedtag(':watch:')->associatedpicto('r_guard_#00')->commit();
        $container->add()->title('Mit offenen Augen schlafen? Kein Problem!')->unlockquantity(40)->associatedtag(':watch:')->associatedpicto('r_guard_#00')->commit();
        $container->add()->title('Immer alles im Blick')->unlockquantity(80)->associatedtag(':watch:')->associatedpicto('r_guard_#00')->commit();
        $container->add()->title('Wachsam')->unlockquantity(120)->associatedtag(':watch:')->associatedpicto('r_guard_#00')->commit();
        $container->add()->title('Paranoid')->unlockquantity(200)->associatedtag(':watch:')->associatedpicto('r_guard_#00')->commit();
        $container->add()->title('Fels in der Brandung')->unlockquantity(400)->associatedtag(':watch:')->associatedpicto('r_guard_#00')->commit();
        $container->add()->title('Uneinnehmbare Festung')->unlockquantity(600)->associatedtag(':watch:')->associatedpicto('r_guard_#00')->commit();
        $container->add()->title('Großer Baumeister')->unlockquantity(20)->associatedtag(':extreme:')->associatedpicto('r_wondrs_#00')->commit();
        $container->add()->title('Großer Architekt')->unlockquantity(50)->associatedtag(':extreme:')->associatedpicto('r_wondrs_#00')->commit();
        $container->add()->title('Freimauer')->unlockquantity(100)->associatedtag(':extreme:')->associatedpicto('r_wondrs_#00')->commit();
        $container->add()->title('Terraformingspezialist')->unlockquantity(150)->associatedtag(':extreme:')->associatedpicto('r_wondrs_#00')->commit();
        $container->add()->title('Allmächtiger Schöpfer')->unlockquantity(200)->associatedtag(':extreme:')->associatedpicto('r_wondrs_#00')->commit();
        $container->add()->title('Archi-Mädlicher Illustrator von Pi')->unlockquantity(250)->associatedtag(':extreme:')->associatedpicto('r_wondrs_#00')->commit();
        $container->add()->title('Muad\'Dib')->unlockquantity(300)->associatedtag(':extreme:')->associatedpicto('r_wondrs_#00')->commit();
        $container->add()->title('Am 7. Tag erschuf er den Fleischkäfig')->unlockquantity(350)->associatedtag(':extreme:')->associatedpicto('r_wondrs_#00')->commit();
        $container->add()->title('Bauherr ohne Sinn und Verstand')->unlockquantity(1)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Erbauer der verlorenen Zeit')->unlockquantity(3)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Erleuchteter Baumeister')->unlockquantity(7)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Maurer aus Leidenschaft')->unlockquantity(10)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Das Unnütze mit dem Angenehmen verbinden')->unlockquantity(15)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Verrückter Architekten-Visionär')->unlockquantity(20)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Ich habe einen Plan')->unlockquantity(30)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Hirnverbrannter Baumeister')->unlockquantity(40)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Meister der Nutzlosigkeit')->unlockquantity(50)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Vereister Ingenieur')->unlockquantity(60)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Wundervoll nutzlos')->unlockquantity(80)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Der Bruce Lee des Spachtels')->unlockquantity(100)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Es ist Zeit für Kathedralen')->unlockquantity(120)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Hast du nichts besseres zu tun?')->unlockquantity(150)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Hohepriesterin des Sonnentempels')->unlockquantity(200)->associatedtag(':wonder:')->associatedpicto('r_ebuild_#00')->commit();
        $container->add()->title('Huldigt den riesigen KVF!')->unlockquantity(5)->associatedtag(':brd:')->associatedpicto('r_ebpmv_#00')->commit();
        $container->add()->title('Obelisk der heutigen Zeit!')->unlockquantity(10)->associatedtag(':brd:')->associatedpicto('r_ebpmv_#00')->commit();
        $container->add()->title('Lebhafter Tribut')->unlockquantity(15)->associatedtag(':brd:')->associatedpicto('r_ebpmv_#00')->commit();
        $container->add()->title('Wird in die Annalen eingehen')->unlockquantity(20)->associatedtag(':brd:')->associatedpicto('r_ebpmv_#00')->commit();
        $container->add()->title('Extra viel Liebe')->unlockquantity(25)->associatedtag(':brd:')->associatedpicto('r_ebpmv_#00')->commit();
        $container->add()->title('Es ist kleiner als im Katalog')->unlockquantity(30)->associatedtag(':brd:')->associatedpicto('r_ebpmv_#00')->commit();
        $container->add()->title('Freude der Stärke 8')->unlockquantity(40)->associatedtag(':brd:')->associatedpicto('r_ebpmv_#00')->commit();
        $container->add()->title('Bewahrer der Freuden')->unlockquantity(50)->associatedtag(':brd:')->associatedpicto('r_ebpmv_#00')->commit();
        $container->add()->title('Ein bisschen näher an den Sternen')->unlockquantity(75)->associatedtag(':brd:')->associatedpicto('r_ebpmv_#00')->commit();
        $container->add()->title('Himmel! Was werden die Nachbarn sagen?')->unlockquantity(100)->associatedtag(':brd:')->associatedpicto('r_ebpmv_#00')->commit();
        $container->add()->title('Das hast du nicht wirklich gebaut?')->unlockquantity(5)->associatedtag(':castle:')->associatedpicto('r_ebcstl_#00')->commit();
        $container->add()->title('Eimerhalter')->unlockquantity(10)->associatedtag(':castle:')->associatedpicto('r_ebcstl_#00')->commit();
        $container->add()->title('Sandverkäufer')->unlockquantity(15)->associatedtag(':castle:')->associatedpicto('r_ebcstl_#00')->commit();
        $container->add()->title('Martinet am Strand')->unlockquantity(20)->associatedtag(':castle:')->associatedpicto('r_ebcstl_#00')->commit();
        $container->add()->title('Ein Spiel für echte Kinder')->unlockquantity(25)->associatedtag(':castle:')->associatedpicto('r_ebcstl_#00')->commit();
        $container->add()->title('Dauermitglied in Micky\'s Club')->unlockquantity(30)->associatedtag(':castle:')->associatedpicto('r_ebcstl_#00')->commit();
        $container->add()->title('Niemals ohne meinen Eimer')->unlockquantity(40)->associatedtag(':castle:')->associatedpicto('r_ebcstl_#00')->commit();
        $container->add()->title('Ein Korn fehlt noch')->unlockquantity(50)->associatedtag(':castle:')->associatedpicto('r_ebcstl_#00')->commit();
        $container->add()->title('Mister Sandman ♫♪')->unlockquantity(75)->associatedtag(':castle:')->associatedpicto('r_ebcstl_#00')->commit();
        $container->add()->title('Nutzt das Vergängliche')->unlockquantity(100)->associatedtag(':castle:')->associatedpicto('r_ebcstl_#00')->commit();
        $container->add()->title('Huldigt den Raben!')->unlockquantity(5)->associatedtag(':crow:')->associatedpicto('r_ebcrow_#00')->commit();
        $container->add()->title('Taube aus der Unterwelt')->unlockquantity(10)->associatedtag(':crow:')->associatedpicto('r_ebcrow_#00')->commit();
        $container->add()->title('Corvid-Spezialist')->unlockquantity(15)->associatedtag(':crow:')->associatedpicto('r_ebcrow_#00')->commit();
        $container->add()->title('Phoenix des Unterholzes')->unlockquantity(20)->associatedtag(':crow:')->associatedpicto('r_ebcrow_#00')->commit();
        $container->add()->title('Edit Piaf')->unlockquantity(25)->associatedtag(':crow:')->associatedpicto('r_ebcrow_#00')->commit();
        $container->add()->title('Vogel der schlechten Vorzeichen')->unlockquantity(30)->associatedtag(':crow:')->associatedpicto('r_ebcrow_#00')->commit();
        $container->add()->title('Kraaaah!')->unlockquantity(40)->associatedtag(':crow:')->associatedpicto('r_ebcrow_#00')->commit();
        $container->add()->title('Er war Leber ...')->unlockquantity(50)->associatedtag(':crow:')->associatedpicto('r_ebcrow_#00')->commit();
        $container->add()->title('John Snow')->unlockquantity(75)->associatedtag(':crow:')->associatedpicto('r_ebcrow_#00')->commit();
        $container->add()->title('Der Rabinator')->unlockquantity(100)->associatedtag(':crow:')->associatedpicto('r_ebcrow_#00')->commit();
        $container->add()->title('Hey wir können die Zombies von hier oben sehen')->unlockquantity(5)->associatedtag(':wheel:')->associatedpicto('r_ebgros_#00')->commit();
        $container->add()->title('Fröhlicher Hamster')->unlockquantity(10)->associatedtag(':wheel:')->associatedpicto('r_ebgros_#00')->commit();
        $container->add()->title('Showman aus der Anderen Welt!')->unlockquantity(15)->associatedtag(':wheel:')->associatedpicto('r_ebgros_#00')->commit();
        $container->add()->title('5. Rad am Wagen')->unlockquantity(20)->associatedtag(':wheel:')->associatedpicto('r_ebgros_#00')->commit();
        $container->add()->title('Mir ist schwindelig')->unlockquantity(25)->associatedtag(':wheel:')->associatedpicto('r_ebgros_#00')->commit();
        $container->add()->title('Hier oben')->unlockquantity(30)->associatedtag(':wheel:')->associatedpicto('r_ebgros_#00')->commit();
        $container->add()->title('Auge der Wüste')->unlockquantity(40)->associatedtag(':wheel:')->associatedpicto('r_ebgros_#00')->commit();
        $container->add()->title('4000 Zombies starren uns an')->unlockquantity(50)->associatedtag(':wheel:')->associatedpicto('r_ebgros_#00')->commit();
        $container->add()->title('Wir drehen frei!')->unlockquantity(75)->associatedtag(':wheel:')->associatedpicto('r_ebgros_#00')->commit();
        $container->add()->title('Durazell')->unlockquantity(15)->associatedtag(':batgun:')->associatedpicto('r_batgun_#00')->commit();
        $container->add()->title('Hüter der Heiligen Batterie')->unlockquantity(25)->associatedtag(':batgun:')->associatedpicto('r_batgun_#00')->commit();
        $container->add()->title('Der Batterienator')->unlockquantity(50)->associatedtag(':batgun:')->associatedpicto('r_batgun_#00')->commit();
        $container->add()->title('Ist es ein Vogel? Ist es ein Flugzeug? Nein, es ist der super Batteriewerfer!')->unlockquantity(75)->associatedtag(':batgun:')->associatedpicto('r_batgun_#00')->commit();
        $container->add()->title('Aufgeladen und kampfbereit')->unlockquantity(100)->associatedtag(':batgun:')->associatedpicto('r_batgun_#00')->commit();
        $container->add()->title('Hey! Willst du meine... Batterie sehen?')->unlockquantity(150)->associatedtag(':batgun:')->associatedpicto('r_batgun_#00')->commit();
        $container->add()->title('Maurerlehrling')->unlockquantity(100)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Maurer')->unlockquantity(200)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Polier')->unlockquantity(400)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Baustellenleiter')->unlockquantity(700)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Architekt (title)')->unlockquantity(1300)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Meisterarchitekt')->unlockquantity(2000)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Oscar Niemeyer')->unlockquantity(3000)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Zement & Garfunkel')->unlockquantity(4000)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Menschliche Ameisenkolonie')->unlockquantity(5000)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Arbeiterhelm und Kupferstiefel')->unlockquantity(6000)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Arbeit ist Gesundheit')->unlockquantity(8000)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Bob der Baumeister')->unlockquantity(10000)->associatedtag(':build:')->associatedpicto('r_buildr_#00')->commit();
        $container->add()->title('Spachtler')->unlockquantity(100)->associatedtag(':rep:')->associatedpicto('r_brep_#00')->commit();
        $container->add()->title('Gewissenhafter Maurer')->unlockquantity(250)->associatedtag(':rep:')->associatedpicto('r_brep_#00')->commit();
        $container->add()->title('Meisterwerke in Gefahr')->unlockquantity(500)->associatedtag(':rep:')->associatedpicto('r_brep_#00')->commit();
        $container->add()->title('Ein Flicken und alles ist wie neu')->unlockquantity(1000)->associatedtag(':rep:')->associatedpicto('r_brep_#00')->commit();
        $container->add()->title('Pisa-Geraderichter')->unlockquantity(1500)->associatedtag(':rep:')->associatedpicto('r_brep_#00')->commit();
        $container->add()->title('Großer Renovator')->unlockquantity(2000)->associatedtag(':rep:')->associatedpicto('r_brep_#00')->commit();
        $container->add()->title('Ein Patch, kein Spiel')->unlockquantity(2500)->associatedtag(':rep:')->associatedpicto('r_brep_#00')->commit();
        $container->add()->title('Ein Riss? Welcher Riss?')->unlockquantity(3000)->associatedtag(':rep:')->associatedpicto('r_brep_#00')->commit();
        $container->add()->title('Das braucht noch 10 Jahre!')->unlockquantity(3500)->associatedtag(':rep:')->associatedpicto('r_brep_#00')->commit();
        $container->add()->title('Kettensägenmassaker')->unlockquantity(5)->associatedtag(':chain:')->associatedpicto('r_tronco_#00')->commit();
        $container->add()->title('Fleisch-Schuldner')->unlockquantity(10)->associatedtag(':chain:')->associatedpicto('r_tronco_#00')->commit();
        $container->add()->title('Bruce Campbell')->unlockquantity(30)->associatedtag(':chain:')->associatedpicto('r_tronco_#00')->commit();
        $container->add()->title('Hobby-Heimwerker')->unlockquantity(15)->associatedtag(':repair:')->associatedpicto('r_repair_#00')->commit();
        $container->add()->title('Techniker')->unlockquantity(30)->associatedtag(':repair:')->associatedpicto('r_repair_#00')->commit();
        $container->add()->title('Meisterbastler ')->unlockquantity(60)->associatedtag(':repair:')->associatedpicto('r_repair_#00')->commit();
        $container->add()->title('Sowas wirft man doch nicht weg!')->unlockquantity(150)->associatedtag(':repair:')->associatedpicto('r_repair_#00')->commit();
        $container->add()->title('Mac Gyver der Außenwelt')->unlockquantity(400)->associatedtag(':repair:')->associatedpicto('r_repair_#00')->commit();
        $container->add()->title('Super Soaker')->unlockquantity(10)->associatedtag(':watergun:')->associatedpicto('r_watgun_#00')->commit();
        $container->add()->title('Wasserwaffen-Spezialist')->unlockquantity(25)->associatedtag(':watergun:')->associatedpicto('r_watgun_#00')->commit();
        $container->add()->title('Hydraulik-Engineering')->unlockquantity(35)->associatedtag(':watergun:')->associatedpicto('r_watgun_#00')->commit();
        $container->add()->title('Abstieg der Atlanteaner')->unlockquantity(60)->associatedtag(':watergun:')->associatedpicto('r_watgun_#00')->commit();
        $container->add()->title('Archäologielehrling')->unlockquantity(50)->associatedtag(':buried:')->associatedpicto('r_digger_#00')->commit();
        $container->add()->title('Archäologe')->unlockquantity(300)->associatedtag(':buried:')->associatedpicto('r_digger_#00')->commit();
        $container->add()->title('Grabungsleiter')->unlockquantity(750)->associatedtag(':buried:')->associatedpicto('r_digger_#00')->commit();
        $container->add()->title('Großer Löcherbuddler')->unlockquantity(1000)->associatedtag(':buried:')->associatedpicto('r_digger_#00')->commit();
        $container->add()->title('Riesenmaulwurf')->unlockquantity(1500)->associatedtag(':buried:')->associatedpicto('r_digger_#00')->commit();
        $container->add()->title('Furchtloser Camper')->unlockquantity(10)->associatedtag(':zen:')->associatedpicto('r_cmplst_#00')->commit();
        $container->add()->title('Waisenkind der Wüste')->unlockquantity(25)->associatedtag(':zen:')->associatedpicto('r_cmplst_#00')->commit();
        $container->add()->title('Unglaubliche Entschlossenheit')->unlockquantity(50)->associatedtag(':zen:')->associatedpicto('r_cmplst_#00')->commit();
        $container->add()->title('Der letzte Überlebende')->unlockquantity(100)->associatedtag(':zen:')->associatedpicto('r_cmplst_#00')->commit();
        $container->add()->title('Ich gehe alleine.')->unlockquantity(150)->associatedtag(':zen:')->associatedpicto('r_cmplst_#00')->commit();
        $container->add()->title('Neil Armstrong der Außenwelt')->unlockquantity(200)->associatedtag(':zen:')->associatedpicto('r_cmplst_#00')->commit();
        $container->add()->title('Lebensmüder Kundschafter')->unlockquantity(5)->associatedtag(':dexplo:')->associatedpicto('r_explo2_#00')->commit();
        $container->add()->title('Draufgängerischer Expeditionsreisender')->unlockquantity(15)->associatedtag(':dexplo:')->associatedpicto('r_explo2_#00')->commit();
        $container->add()->title('Nervenkitzelsucher')->unlockquantity(30)->associatedtag(':dexplo:')->associatedpicto('r_explo2_#00')->commit();
        $container->add()->title('Christopher Kolumbus')->unlockquantity(70)->associatedtag(':dexplo:')->associatedpicto('r_explo2_#00')->commit();
        # $container->add()->title('Neil Armstrong der Außenwelt')->unlockquantity(100)->associatedtag(':dexplo:')->associatedpicto('r_explo2_#00')->commit(); #
        $container->add()->title('Bis zur Unendlichkeit... und noch viel weiter!')->unlockquantity(150)->associatedtag(':dexplo:')->associatedpicto('r_explo2_#00')->commit();
        $container->add()->title('Indiana Jones und die Ruinen der Aussenwelt')->unlockquantity(300)->associatedtag(':dexplo:')->associatedpicto('r_explo2_#00')->commit();
        $container->add()->title('Wenn ich das nur vorher gewusst hätte...')->unlockquantity(5)->associatedtag(':ruin:')->associatedpicto('r_ruine_#00')->commit();
        $container->add()->title('Verwegener Wanderer')->unlockquantity(10)->associatedtag(':ruin:')->associatedpicto('r_ruine_#00')->commit();
        $container->add()->title('Tunnelblicker')->unlockquantity(20)->associatedtag(':ruin:')->associatedpicto('r_ruine_#00')->commit();
        $container->add()->title('Im Irrgarten')->unlockquantity(50)->associatedtag(':ruin:')->associatedpicto('r_ruine_#00')->commit();
        $container->add()->title('Inklusive Kompass')->unlockquantity(100)->associatedtag(':ruin:')->associatedpicto('r_ruine_#00')->commit();
        $container->add()->title('Begrabener Freiwilliger')->unlockquantity(150)->associatedtag(':ruin:')->associatedpicto('r_ruine_#00')->commit();
        $container->add()->title('Tomb Raider')->unlockquantity(200)->associatedtag(':ruin:')->associatedpicto('r_ruine_#00')->commit();
        $container->add()->title('Labyrinth-Gollum')->unlockquantity(250)->associatedtag(':ruin:')->associatedpicto('r_ruine_#00')->commit();
        $container->add()->title('Labyrinth-Meister MB')->unlockquantity(400)->associatedtag(':ruin:')->associatedpicto('r_ruine_#00')->commit();
        $container->add()->title('Wo klemmt\'s?')->unlockquantity(1)->associatedtag(':lock:')->associatedpicto('r_door_#00')->commit();
        $container->add()->title('Dietrich')->unlockquantity(5)->associatedtag(':lock:')->associatedpicto('r_door_#00')->commit();
        $container->add()->title('Sesam, öffne dich...')->unlockquantity(10)->associatedtag(':lock:')->associatedpicto('r_door_#00')->commit();
        $container->add()->title('Türöffner')->unlockquantity(15)->associatedtag(':lock:')->associatedpicto('r_door_#00')->commit();
        $container->add()->title('Gentleman-Einbrecher')->unlockquantity(20)->associatedtag(':lock:')->associatedpicto('r_door_#00')->commit();
        $container->add()->title('Schlüsseldienst')->unlockquantity(30)->associatedtag(':lock:')->associatedpicto('r_door_#00')->commit();
        $container->add()->title('Zerberus')->unlockquantity(50)->associatedtag(':lock:')->associatedpicto('r_door_#00')->commit();
        $container->add()->title('Meister der Schlüssel')->unlockquantity(100)->associatedtag(':lock:')->associatedpicto('r_door_#00')->commit();
        $container->add()->title('Brutalo')->unlockquantity(100)->associatedtag(':zombie:')->associatedpicto('r_killz_#00')->commit();
        $container->add()->title('Verstümmler')->unlockquantity(200)->associatedtag(':zombie:')->associatedpicto('r_killz_#00')->commit();
        $container->add()->title('Killer')->unlockquantity(300)->associatedtag(':zombie:')->associatedpicto('r_killz_#00')->commit();
        $container->add()->title('Kadaverentsorger')->unlockquantity(800)->associatedtag(':zombie:')->associatedpicto('r_killz_#00')->commit();
        $container->add()->title('Vernichter')->unlockquantity(2000)->associatedtag(':zombie:')->associatedpicto('r_killz_#00')->commit();
        $container->add()->title('Schlächter')->unlockquantity(4000)->associatedtag(':zombie:')->associatedpicto('r_killz_#00')->commit();
        $container->add()->title('Friedensstifter')->unlockquantity(6000)->associatedtag(':zombie:')->associatedpicto('r_killz_#00')->commit();
        $container->add()->title('Alptraum der Traumlosen')->unlockquantity(10000)->associatedtag(':zombie:')->associatedpicto('r_killz_#00')->commit();
        $container->add()->title('Du nennst das ein Messer? DAS ist ein Messer!')->unlockquantity(15000)->associatedtag(':zombie:')->associatedpicto('r_killz_#00')->commit();
        $container->add()->title('Hans im Glück')->unlockquantity(5)->associatedtag(':chest:')->associatedpicto('r_chstxl_#00')->commit();
        $container->add()->title('Vierklettriges Kleeblatt')->unlockquantity(10)->associatedtag(':chest:')->associatedpicto('r_chstxl_#00')->commit();
        $container->add()->title('Fortuna')->unlockquantity(15)->associatedtag(':chest:')->associatedpicto('r_chstxl_#00')->commit();
        $container->add()->title('Gontran Happiness')->unlockquantity(20)->associatedtag(':chest:')->associatedpicto('r_chstxl_#00')->commit();
        $container->add()->title('Lucky 7')->unlockquantity(30)->associatedtag(':chest:')->associatedpicto('r_chstxl_#00')->commit();
        $container->add()->title('Money for Nothing')->unlockquantity(50)->associatedtag(':chest:')->associatedpicto('r_chstxl_#00')->commit();
        $container->add()->title('Ultimate Fighter')->unlockquantity(20)->associatedtag(':fight:')->associatedpicto('r_wrestl_#00')->commit();
        $container->add()->title('Wilde Bestie')->unlockquantity(100)->associatedtag(':fight:')->associatedpicto('r_wrestl_#00')->commit();
        $container->add()->title('Rambos Großvater')->unlockquantity(200)->associatedtag(':fight:')->associatedpicto('r_wrestl_#00')->commit();
        $container->add()->title('Absolut keine Angst!')->unlockquantity(400)->associatedtag(':fight:')->associatedpicto('r_wrestl_#00')->commit();
        $container->add()->title('Barhändiger Stripper')->unlockquantity(600)->associatedtag(':fight:')->associatedpicto('r_wrestl_#00')->commit();
        $container->add()->title('Stürmischer Kundschafter')->unlockquantity(15)->associatedtag(':explo:')->associatedpicto('r_explor_#00')->commit();
        $container->add()->title('Furchtloser Abenteurer')->unlockquantity(30)->associatedtag(':explo:')->associatedpicto('r_explor_#00')->commit();
        $container->add()->title('Wagemutiger Trapper')->unlockquantity(70)->associatedtag(':explo:')->associatedpicto('r_explor_#00')->commit();
        $container->add()->title('Wikinger')->unlockquantity(150)->associatedtag(':explo:')->associatedpicto('r_explor_#00')->commit();
        $container->add()->title('Außenweltreiseführer')->unlockquantity(200)->associatedtag(':explo:')->associatedpicto('r_explor_#00')->commit();
        $container->add()->title('Ich habe die Erde umrundet... zweimal!')->unlockquantity(250)->associatedtag(':explo:')->associatedpicto('r_explor_#00')->commit();
        $container->add()->title('Internet Explorer')->unlockquantity(300)->associatedtag(':explo:')->associatedpicto('r_explor_#00')->commit();
        $container->add()->title('Ich hab sogar das Klo abgesucht!')->unlockquantity(350)->associatedtag(':explo:')->associatedpicto('r_explor_#00')->commit();
        $container->add()->title('Sind wir schon da?')->unlockquantity(400)->associatedtag(':explo:')->associatedpicto('r_explor_#00')->commit();
        $container->add()->title('Außenweltschläfer')->unlockquantity(10)->associatedtag(':camper:')->associatedpicto('r_camp_#00')->commit();
        $container->add()->title('Allein in dieser Welt')->unlockquantity(25)->associatedtag(':camper:')->associatedpicto('r_camp_#00')->commit();
        $container->add()->title('Der mit den Zombies tanzt')->unlockquantity(50)->associatedtag(':camper:')->associatedpicto('r_camp_#00')->commit();
        $container->add()->title('Ich sehe überall Tote!')->unlockquantity(75)->associatedtag(':camper:')->associatedpicto('r_camp_#00')->commit();
        $container->add()->title('Ich komme heute Nacht nicht heim...')->unlockquantity(100)->associatedtag(':camper:')->associatedpicto('r_camp_#00')->commit();
        $container->add()->title('Ein Mann gegen die Außenwelt')->unlockquantity(150)->associatedtag(':camper:')->associatedpicto('r_camp_#00')->commit();
        $container->add()->title('Stadtallergie')->unlockquantity(200)->associatedtag(':camper:')->associatedpicto('r_camp_#00')->commit();
        $container->add()->title('Wo ich hinguck, seh ich Gegend.')->unlockquantity(250)->associatedtag(':camper:')->associatedpicto('r_camp_#00')->commit();
        $container->add()->title('Runaway Michael')->unlockquantity(300)->associatedtag(':camper:')->associatedpicto('r_camp_#00')->commit();
        $container->add()->title('Ohne Dach oder Leber')->unlockquantity(350)->associatedtag(':camper:')->associatedpicto('r_camp_#00')->commit();
        $container->add()->title('Neugieriger Leser')->unlockquantity(5)->associatedtag(':rptext:')->associatedpicto('r_rp_#00')->commit();
        $container->add()->title('Eifriger Leser')->unlockquantity(10)->associatedtag(':rptext:')->associatedpicto('r_rp_#00')->commit();
        $container->add()->title('Wüstenhistoriker')->unlockquantity(20)->associatedtag(':rptext:')->associatedpicto('r_rp_#00')->commit();
        $container->add()->title('Bibliothekar')->unlockquantity(30)->associatedtag(':rptext:')->associatedpicto('r_rp_#00')->commit();
        $container->add()->title('Archivar')->unlockquantity(40)->associatedtag(':rptext:')->associatedpicto('r_rp_#00')->commit();
        $container->add()->title('Erinnerungsträger')->unlockquantity(60)->associatedtag(':rptext:')->associatedpicto('r_rp_#00')->commit();
        $container->add()->title('Erinnerungen an die Zivilisation')->unlockquantity(100)->associatedtag(':rptext:')->associatedpicto('r_rp_#00')->commit();
        $container->add()->title('Twinoid ist tabu')->unlockquantity(20)->associatedtag(':clean:')->associatedpicto('r_nodrug_#00')->commit();
        $container->add()->title('Keine Macht den Drogen')->unlockquantity(75)->associatedtag(':clean:')->associatedpicto('r_nodrug_#00')->commit();
        $container->add()->title('Sowas fasse ICH nicht an')->unlockquantity(150)->associatedtag(':clean:')->associatedpicto('r_nodrug_#00')->commit();
        $container->add()->title('Vorbild für die Jugend')->unlockquantity(500)->associatedtag(':clean:')->associatedpicto('r_nodrug_#00')->commit();
        $container->add()->title('Champions nehmen keine Drogen!')->unlockquantity(1000)->associatedtag(':clean:')->associatedpicto('r_nodrug_#00')->commit();
        $container->add()->title('Medikamentetester')->unlockquantity(50)->associatedtag(':experimental:')->associatedpicto('r_cobaye_#00')->commit();
        $container->add()->title('Laborratte')->unlockquantity(100)->associatedtag(':experimental:')->associatedpicto('r_cobaye_#00')->commit();
        $container->add()->title('Pille palle, 3 Tage wach!')->unlockquantity(150)->associatedtag(':experimental:')->associatedpicto('r_cobaye_#00')->commit();
        $container->add()->title('Timothy Leary')->unlockquantity(200)->associatedtag(':experimental:')->associatedpicto('r_cobaye_#00')->commit();
        $container->add()->title('Ich sehe ein Blauuuuuuues Tal')->unlockquantity(250)->associatedtag(':experimental:')->associatedpicto('r_cobaye_#00')->commit();
        $container->add()->title('Menschenfleischliebhaber')->unlockquantity(10)->associatedtag(':cannibal:')->associatedpicto('r_cannib_#00')->commit();
        $container->add()->title('Hannibalfan')->unlockquantity(40)->associatedtag(':cannibal:')->associatedpicto('r_cannib_#00')->commit();
        $container->add()->title('Totmacher')->unlockquantity(80)->associatedtag(':cannibal:')->associatedpicto('r_cannib_#00')->commit();
        $container->add()->title('Jeffrey Dahmer')->unlockquantity(120)->associatedtag(':cannibal:')->associatedpicto('r_cannib_#00')->commit();
        # $container->add()->title('Fido')->unlockquantity(150)->associatedtag(':cannibal:')->associatedpicto('r_cannib_#00')->commit(); #
        $container->add()->title('Fast schon ein Zombie...')->unlockquantity(180)->associatedtag(':cannibal:')->associatedpicto('r_cannib_#00')->commit();
        $container->add()->title('Schmeckt am besten wenn\'s noch schreit!')->unlockquantity(250)->associatedtag(':cannibal:')->associatedpicto('r_cannib_#00')->commit();
        $container->add()->title('Die Macht der Proteine')->unlockquantity(500)->associatedtag(':cannibal:')->associatedpicto('r_cannib_#00')->commit();
        $container->add()->title('Nackt und Zerfleischt')->unlockquantity(1000)->associatedtag(':cannibal:')->associatedpicto('r_cannib_#00')->commit();
        $container->add()->title('Zombieliebling')->unlockquantity(10)->associatedtag(':lms:')->associatedpicto('r_surlst_#00')->commit();
        $container->add()->title('Letzter Überlebender')->unlockquantity(15)->associatedtag(':lms:')->associatedpicto('r_surlst_#00')->commit();
        $container->add()->title('Unzerstörbar')->unlockquantity(30)->associatedtag(':lms:')->associatedpicto('r_surlst_#00')->commit();
        $container->add()->title('Allein gegen die Horde')->unlockquantity(50)->associatedtag(':lms:')->associatedpicto('r_surlst_#00')->commit();
        $container->add()->title('Chuck Norris\' Ebenbild')->unlockquantity(100)->associatedtag(':lms:')->associatedpicto('r_surlst_#00')->commit();
        $container->add()->title('Ich bin in der Hölle aufgewachsen.')->unlockquantity(5)->associatedtag(':hclms:')->associatedpicto('r_suhard_#00')->commit();
        $container->add()->title('Es war wirklich zu einfach.')->unlockquantity(10)->associatedtag(':hclms:')->associatedpicto('r_suhard_#00')->commit();
        $container->add()->title('Ich fresse Nägel und scheiße Kugeln!')->unlockquantity(20)->associatedtag(':hclms:')->associatedpicto('r_suhard_#00')->commit();
        $container->add()->title('Pandämonium? Hah. Einfach.')->unlockquantity(40)->associatedtag(':hclms:')->associatedpicto('r_suhard_#00')->commit();
        $container->add()->title('Apostel des Pandämoniums')->unlockquantity(100)->associatedtag(':hclms:')->associatedpicto('r_suhard_#00')->commit();
        $container->add()->title('Teilweise verrottet')->unlockquantity(20)->associatedtag(':infect:')->associatedpicto('r_dinfec_#00')->commit();
        $container->add()->title('Virenschleuder')->unlockquantity(40)->associatedtag(':infect:')->associatedpicto('r_dinfec_#00')->commit();
        $container->add()->title('Gedärmeauskotzer')->unlockquantity(75)->associatedtag(':infect:')->associatedpicto('r_dinfec_#00')->commit();
        $container->add()->title('Seuchenherd')->unlockquantity(100)->associatedtag(':infect:')->associatedpicto('r_dinfec_#00')->commit();
        $container->add()->title('Ich habe Magenschmerzen...')->unlockquantity(150)->associatedtag(':infect:')->associatedpicto('r_dinfec_#00')->commit();
        $container->add()->title('Verirrter Ausflügler')->unlockquantity(20)->associatedtag(':night:')->associatedpicto('r_doutsd_#00')->commit();
        $container->add()->title('Nächtlicher Spaziergänger')->unlockquantity(100)->associatedtag(':night:')->associatedpicto('r_doutsd_#00')->commit();
        $container->add()->title('Mir ist kalt hier draußen...')->unlockquantity(250)->associatedtag(':night:')->associatedpicto('r_doutsd_#00')->commit();
        $container->add()->title('Vertrauenswürdiger Bürger')->unlockquantity(2)->associatedtag(':ranked:')->associatedpicto('r_winbas_#00')->commit();
        $container->add()->title('Sehr erfahrener Bürger')->unlockquantity(5)->associatedtag(':ranked:')->associatedpicto('r_winbas_#00')->commit();
        $container->add()->title('Vorbild für das Volk')->unlockquantity(10)->associatedtag(':ranked:')->associatedpicto('r_winbas_#00')->commit();
        $container->add()->title('Richtwert der Gemeinschaft')->unlockquantity(15)->associatedtag(':ranked:')->associatedpicto('r_winbas_#00')->commit();
        $container->add()->title('Berühmter Veteran')->unlockquantity(20)->associatedtag(':ranked:')->associatedpicto('r_winbas_#00')->commit();
        $container->add()->title('Anfängerleiche')->unlockquantity(2)->associatedtag(':part:')->associatedpicto('r_winthi_#00')->commit();
        $container->add()->title('Rabenfreund')->unlockquantity(5)->associatedtag(':part:')->associatedpicto('r_winthi_#00')->commit();
        $container->add()->title('Dehydrationskollege')->unlockquantity(10)->associatedtag(':part:')->associatedpicto('r_winthi_#00')->commit();
        $container->add()->title('Lebender Mythos')->unlockquantity(1)->associatedtag(':legend:')->associatedpicto('r_wintop_#00')->commit();
        $container->add()->title('Ich bin eine Legende')->unlockquantity(2)->associatedtag(':legend:')->associatedpicto('r_wintop_#00')->commit();
        $container->add()->title('Hör auf mich, wenn du überleben möchtest')->unlockquantity(3)->associatedtag(':legend:')->associatedpicto('r_wintop_#00')->commit();
        $container->add()->title('Netter Kerl')->unlockquantity(1)->associatedtag(':goodg:')->associatedpicto('r_goodg_#00')->commit();
        $container->add()->title('Zeuge der großen Verseuchung')->unlockquantity(1)->associatedtag(':ginfec:')->associatedpicto('r_ginfec_#00')->commit();
        $container->add()->title('Alter Hase')->unlockquantity(1)->associatedtag(':beta:')->associatedpicto('r_beta_#00')->commit();
        $container->add()->title('Jedes Los gewinnt')->unlockquantity(1)->associatedtag(':bgum:')->associatedpicto('r_bgum_#00')->commit();
        $container->add()->title('Zinker')->unlockquantity(5)->associatedtag(':bgum:')->associatedpicto('r_bgum_#00')->commit();
        $container->add()->title('Bingo')->unlockquantity(10)->associatedtag(':bgum:')->associatedpicto('r_bgum_#00')->commit();
        $container->add()->title('Sudoku ist anders')->unlockquantity(15)->associatedtag(':bgum:')->associatedpicto('r_bgum_#00')->commit();
        $container->add()->title('Siebenseitiger Würfel')->unlockquantity(20)->associatedtag(':bgum:')->associatedpicto('r_bgum_#00')->commit();
        $container->add()->title('Einarmiger Bandit')->unlockquantity(30)->associatedtag(':bgum:')->associatedpicto('r_bgum_#00')->commit();
        $container->add()->title('Seelenführer der Gemeinschaft')->unlockquantity(50)->associatedtag(':bgum:')->associatedpicto('r_bgum_#00')->commit();
        $container->add()->title('Charismatischer Prophet')->unlockquantity(100)->associatedtag(':bgum:')->associatedpicto('r_bgum_#00')->commit();
        $container->add()->title('Liebling des Raben')->unlockquantity(150)->associatedtag(':bgum:')->associatedpicto('r_bgum_#00')->commit();
        $container->add()->title('Motivierter Messebesucher')->unlockquantity(1)->associatedtag(':fjv2:')->associatedpicto('r_fjv2_#00')->commit();
        $container->add()->title('Verdammt in Saarbrücken')->unlockquantity(1)->associatedtag(':fjvani:')->associatedpicto('r_fjvani_#00')->commit();
        $container->add()->title('FJV\'08 Kanonenfutter')->unlockquantity(1)->associatedtag(':fjv:')->associatedpicto('r_fjv_#00')->commit();
        $container->add()->title('Kleiner Guru')->unlockquantity(1)->associatedtag(':rrefer:')->associatedpicto('r_rrefer_#00')->commit();
        $container->add()->title('Überzeugender Guru')->unlockquantity(3)->associatedtag(':rrefer:')->associatedpicto('r_rrefer_#00')->commit();
        $container->add()->title('Frischfleischhändler')->unlockquantity(5)->associatedtag(':rrefer:')->associatedpicto('r_rrefer_#00')->commit();
        $container->add()->title('Seelenhändler')->unlockquantity(10)->associatedtag(':rrefer:')->associatedpicto('r_rrefer_#00')->commit();
        $container->add()->title('Sehr überzeugender Pate')->unlockquantity(15)->associatedtag(':rrefer:')->associatedpicto('r_rrefer_#00')->commit();
        $container->add()->title('Wüstenspekulant')->unlockquantity(20)->associatedtag(':rrefer:')->associatedpicto('r_rrefer_#00')->commit();
        $container->add()->title('Seelentrader')->unlockquantity(25)->associatedtag(':rrefer:')->associatedpicto('r_rrefer_#00')->commit();
        $container->add()->title('Scientologe')->unlockquantity(50)->associatedtag(':rrefer:')->associatedpicto('r_rrefer_#00')->commit();
        $container->add()->title('Komm auf die dunkle Seite der Macht!')->unlockquantity(100)->associatedtag(':rrefer:')->associatedpicto('r_rrefer_#00')->commit();
        $container->add()->title('Warren Buffet der Außenwelt')->unlockquantity(150)->associatedtag(':rrefer:')->associatedpicto('r_rrefer_#00')->commit();
        $container->add()->title('Held der Community!')->unlockquantity(1)->associatedtag(':comu:')->associatedpicto('r_comu_#00')->commit();
        $container->add()->title('Bringt Sachen ins Rollen!')->unlockquantity(1)->associatedtag(':comu2:')->associatedpicto('r_comu2_#00')->commit();
        $container->add()->title('Nobler Spender')->unlockquantity(10)->associatedtag(':share:')->associatedpicto('r_share_#00')->commit();
        $container->add()->title('Immer zur Stelle')->unlockquantity(25)->associatedtag(':share:')->associatedpicto('r_share_#00')->commit();
        $container->add()->title('Samariter')->unlockquantity(50)->associatedtag(':share:')->associatedpicto('r_share_#00')->commit();
        $container->add()->title('Freigiebiger Bürger')->unlockquantity(100)->associatedtag(':share:')->associatedpicto('r_share_#00')->commit();
        $container->add()->title('Messias')->unlockquantity(150)->associatedtag(':share:')->associatedpicto('r_share_#00')->commit();
        $container->add()->title('Mein Körper ist bereit!')->unlockquantity(250)->associatedtag(':share:')->associatedpicto('r_share_#00')->commit();
        $container->add()->title('Ultimatives Opfer')->unlockquantity(400)->associatedtag(':share:')->associatedpicto('r_share_#00')->commit();
        $container->add()->title('Der Weihnachtsmann ist ein Schlawiner')->unlockquantity(10)->associatedtag(':santa:')->associatedpicto('r_santac_#00')->commit();
        $container->add()->title('Santa Klaus ist ein Schummler')->unlockquantity(25)->associatedtag(':santa:')->associatedpicto('r_santac_#00')->commit();
        $container->add()->title('Santa Klaus ist Abfall')->unlockquantity(50)->associatedtag(':santa:')->associatedpicto('r_santac_#00')->commit();
        $container->add()->title('Santa Klaus ist Abschaum')->unlockquantity(75)->associatedtag(':santa:')->associatedpicto('r_santac_#00')->commit();
        $container->add()->title('Hängt Santa Klaus!')->unlockquantity(100)->associatedtag(':santa:')->associatedpicto('r_santac_#00')->commit();
        $container->add()->title('Treffen der 4. Art')->unlockquantity(2)->associatedtag(':collect:')->associatedpicto('r_collec_#00')->commit();
        $container->add()->title('Hast Du mal Feuer?')->unlockquantity(10)->associatedtag(':collect:')->associatedpicto('r_collec_#00')->commit();
        $container->add()->title('Medium mit Preisnachlass')->unlockquantity(20)->associatedtag(':collect:')->associatedpicto('r_collec_#00')->commit();
        $container->add()->title('Amophilis Psychotropes')->unlockquantity(30)->associatedtag(':collect:')->associatedpicto('r_collec_#00')->commit();
        $container->add()->title('Blauer Feuerspucker')->unlockquantity(50)->associatedtag(':collect:')->associatedpicto('r_collec_#00')->commit();
        $container->add()->title('I see dead people 0_0')->unlockquantity(80)->associatedtag(':collect:')->associatedpicto('r_collec_#00')->commit();
        $container->add()->title('Soul Man')->unlockquantity(120)->associatedtag(':collect:')->associatedpicto('r_collec_#00')->commit();
        $container->add()->title('Lebenssammler')->unlockquantity(180)->associatedtag(':collect:')->associatedpicto('r_collec_#00')->commit();
        $container->add()->title('Schnitter der Aussenwelt')->unlockquantity(300)->associatedtag(':collect:')->associatedpicto('r_collec_#00')->commit();
        $container->add()->title('Bei meiner Seel')->unlockquantity(100)->associatedtag(':ptame:')->associatedpicto('r_ptame_#00')->commit();
        $container->add()->title('Für immer und seelich')->unlockquantity(500)->associatedtag(':ptame:')->associatedpicto('r_ptame_#00')->commit();
        $container->add()->title('Noble Seele')->unlockquantity(1000)->associatedtag(':ptame:')->associatedpicto('r_ptame_#00')->commit();
        $container->add()->title('Beseelt')->unlockquantity(2000)->associatedtag(':ptame:')->associatedpicto('r_ptame_#00')->commit();
        $container->add()->title('Reinkarnator')->unlockquantity(3000)->associatedtag(':ptame:')->associatedpicto('r_ptame_#00')->commit();
        $container->add()->title('Göttliche Seele')->unlockquantity(5000)->associatedtag(':ptame:')->associatedpicto('r_ptame_#00')->commit();
        $container->add()->title('Open-chakra')->unlockquantity(7000)->associatedtag(':ptame:')->associatedpicto('r_ptame_#00')->commit();
        $container->add()->title('Tausend-und-ein-Leben')->unlockquantity(9000)->associatedtag(':ptame:')->associatedpicto('r_ptame_#00')->commit();
        $container->add()->title('Buddha')->unlockquantity(12000)->associatedtag(':ptame:')->associatedpicto('r_ptame_#00')->commit();
        $container->add()->title('Ich bin ein Gott! Ich werde ewig leben!')->unlockquantity(1)->associatedtag(':ermwin:')->associatedpicto('r_ermwin_#00')->commit();
        $container->add()->title('Eine Stadt sie zu knechten!')->unlockquantity(1)->associatedtag(':cott:')->associatedpicto('r_cott_#00')->commit();
        $container->add()->title('Verrückter Skeptiker')->unlockquantity(10)->associatedtag(':mystic:')->associatedpicto('r_mystic_#00')->commit();
        $container->add()->title('Seelenknipser')->unlockquantity(25)->associatedtag(':mystic:')->associatedpicto('r_mystic_#00')->commit();
        $container->add()->title('Wächter der Seelen')->unlockquantity(75)->associatedtag(':mystic:')->associatedpicto('r_mystic_#00')->commit();
        $container->add()->title('Die Wahrheit ist irgendwo da draußen')->unlockquantity(150)->associatedtag(':mystic:')->associatedpicto('r_mystic_#00')->commit();
        $container->add()->title('Ich glaube!')->unlockquantity(300)->associatedtag(':mystic:')->associatedpicto('r_mystic_#00')->commit();
        $container->add()->title('Sektenmitglied')->unlockquantity(800)->associatedtag(':mystic:')->associatedpicto('r_mystic_#00')->commit();
        $container->add()->title('Kosmischer Anführer')->unlockquantity(1500)->associatedtag(':mystic:')->associatedpicto('r_mystic_#00')->commit();
        $container->add()->title('Rauch? Welcher Rauch?')->unlockquantity(10)->associatedtag(':nuke:')->associatedpicto('r_dnucl_#00')->commit();
        $container->add()->title('Leckstopper')->unlockquantity(20)->associatedtag(':nuke:')->associatedpicto('r_dnucl_#00')->commit();
        $container->add()->title('Licht in der Nacht')->unlockquantity(30)->associatedtag(':nuke:')->associatedpicto('r_dnucl_#00')->commit();
        $container->add()->title('RadioactiveMan')->unlockquantity(50)->associatedtag(':nuke:')->associatedpicto('r_dnucl_#00')->commit();
        $container->add()->title('Strahlender Bürger')->unlockquantity(60)->associatedtag(':nuke:')->associatedpicto('r_dnucl_#00')->commit();
        $container->add()->title('Kabum! Der Reaktor mach KABUM!!!')->unlockquantity(80)->associatedtag(':nuke:')->associatedpicto('r_dnucl_#00')->commit();
        $container->add()->title('Atompilzsammler')->unlockquantity(90)->associatedtag(':nuke:')->associatedpicto('r_dnucl_#00')->commit();
        $container->add()->title('Bis auf die Seele verstrahlt')->unlockquantity(100)->associatedtag(':nuke:')->associatedpicto('r_dnucl_#00')->commit();
        $container->add()->title('Ich steh auf Fusion!')->unlockquantity(120)->associatedtag(':nuke:')->associatedpicto('r_dnucl_#00')->commit();
        $container->add()->title('Kung-Fu-Sion')->unlockquantity(150)->associatedtag(':nuke:')->associatedpicto('r_dnucl_#00')->commit();
        $container->add()->title('Hölle, das esse ich jeden Morgen.')->unlockquantity(50)->associatedtag(':pande:')->associatedpicto('r_pande_#00')->commit();
        $container->add()->title('Abonnent der Pandämoniumsauna')->unlockquantity(150)->associatedtag(':pande:')->associatedpicto('r_pande_#00')->commit();
        $container->add()->title('Pandämonium ist meine Liebe!')->unlockquantity(300)->associatedtag(':pande:')->associatedpicto('r_pande_#00')->commit();
        $container->add()->title('Luzifers Tanzpartner')->unlockquantity(500)->associatedtag(':pande:')->associatedpicto('r_pande_#00')->commit();
        $container->add()->title('Ultimativer Horden-Erkunder')->unlockquantity(1000)->associatedtag(':pande:')->associatedpicto('r_pande_#00')->commit();
        $container->add()->title('Irische Taschen sind prall gefüllt!')->unlockquantity(10)->associatedtag(':lepre:')->associatedpicto('r_lepre_#00')->commit();
        $container->add()->title('Wo ist mein Topf voll Gold, diebische Elster!')->unlockquantity(25)->associatedtag(':lepre:')->associatedpicto('r_lepre_#00')->commit();
        $container->add()->title('Dieser Kobold ist unaufhaltbar.')->unlockquantity(50)->associatedtag(':lepre:')->associatedpicto('r_lepre_#00')->commit();
        $container->add()->title('Verbrennt ihn! Sieh nach ob seine Asche grün wird!')->unlockquantity(75)->associatedtag(':lepre:')->associatedpicto('r_lepre_#00')->commit();
        $container->add()->title('Ein Wohnwagen ohne Räder???')->unlockquantity(100)->associatedtag(':lepre:')->associatedpicto('r_lepre_#00')->commit();
        $container->add()->title('Mitglied des Roten Kreuzes')->unlockquantity(1)->associatedtag(':easter:')->associatedpicto('r_paques_#00')->commit();
        $container->add()->title('Ich bin geheilt')->unlockquantity(1)->associatedtag(':gsp:')->associatedpicto('r_gsp_#00')->commit();
        $container->add()->title('Keine Fehler hi&e%12;r')->unlockquantity(1)->associatedtag(':ripflash:')->associatedpicto('r_ripflash_#00')->commit();
        $container->add()->title('Patient Null')->unlockquantity(1)->associatedtag(':beta2:')->associatedpicto('r_beta2_#00')->commit();
        $container->add()->title('Es ist der Tod der mich fürchten sollte!')->unlockquantity(1)->associatedtag(':derwin:')->associatedpicto('r_derwin_#00')->commit();
        $container->add()->title('Sandmann')->unlockquantity(10)->associatedtag(':sand:')->associatedpicto('r_sandb_#00')->commit();
        $container->add()->title('Sandy Maverick')->unlockquantity(50)->associatedtag(':sand:')->associatedpicto('r_sandb_#00')->commit();
        $container->add()->title('Sandsteiniger')->unlockquantity(100)->associatedtag(':sand:')->associatedpicto('r_sandb_#00')->commit();
        $container->add()->title('Sandkasten-Scharfschütze')->unlockquantity(250)->associatedtag(':sand:')->associatedpicto('r_sandb_#00')->commit();
        $container->add()->title('Wegweiser')->unlockquantity(300)->associatedtag(':noob:')->associatedpicto('r_guide_#00')->commit();
        $container->add()->title('Praktischer Begleiter')->unlockquantity(1000)->associatedtag(':noob:')->associatedpicto('r_guide_#00')->commit();
        $container->add()->title('Erleuchteter Anführer')->unlockquantity(2500)->associatedtag(':noob:')->associatedpicto('r_guide_#00')->commit();
        $container->add()->title('Erleuchteter Prediger')->unlockquantity(5000)->associatedtag(':noob:')->associatedpicto('r_guide_#00')->commit();
        $container->add()->title('Guru der Liebe')->unlockquantity(8000)->associatedtag(':noob:')->associatedpicto('r_guide_#00')->commit();
        $container->add()->title('Höret meine Stimme')->unlockquantity(15000)->associatedtag(':noob:')->associatedpicto('r_guide_#00')->commit();
        $container->add()->title('Universelle Muse')->unlockquantity(30000)->associatedtag(':noob:')->associatedpicto('r_guide_#00')->commit();
        $container->add()->title('Zeuge des Armageddon')->unlockquantity(1)->associatedtag(':arma:')->associatedpicto('r_armag_#00')->commit();
        $container->add()->title('Ewiger Zweiter')->unlockquantity(5)->associatedtag(':last:')->associatedpicto('r_surgrp_#00')->commit();
        $container->add()->title('Ein Wächter stirbt, aber gibt niemals auf')->unlockquantity(10)->associatedtag(':last:')->associatedpicto('r_surgrp_#00')->commit();
        $container->add()->title('Der Zweitletzte Mohikaner')->unlockquantity(20)->associatedtag(':last:')->associatedpicto('r_surgrp_#00')->commit();
        $container->add()->title('Faaaaaaaast, ach verdammt')->unlockquantity(30)->associatedtag(':last:')->associatedpicto('r_surgrp_#00')->commit();
        $container->add()->title('Bis zum Ende und einen Schritt weiter')->unlockquantity(40)->associatedtag(':last:')->associatedpicto('r_surgrp_#00')->commit();
        $container->add()->title('Schließt die Ränke und haltet durch')->unlockquantity(60)->associatedtag(':last:')->associatedpicto('r_surgrp_#00')->commit();
        $container->add()->title('Hallo... ist da draußen jemand?')->unlockquantity(100)->associatedtag(':last:')->associatedpicto('r_surgrp_#00')->commit();
        $container->add()->title('Haltet eure Position!')->unlockquantity(150)->associatedtag(':last:')->associatedpicto('r_surgrp_#00')->commit();
        $container->add()->title('Nur ein Finger')->unlockquantity(30)->associatedtag(':alc:')->associatedpicto('r_alcool_#00')->commit();
        $container->add()->title('Plünderer der Schnapsläden')->unlockquantity(60)->associatedtag(':alc:')->associatedpicto('r_alcool_#00')->commit();
        $container->add()->title('Hennessy Highwayman')->unlockquantity(150)->associatedtag(':alc:')->associatedpicto('r_alcool_#00')->commit();
        $container->add()->title('Barney Gumble der Außenwelt')->unlockquantity(300)->associatedtag(':alc:')->associatedpicto('r_alcool_#00')->commit();
        $container->add()->title('Fass das Saufen lieber sein')->unlockquantity(400)->associatedtag(':alc:')->associatedpicto('r_alcool_#00')->commit();
        $container->add()->title('Gib mir was zu saufen oder es knallt!')->unlockquantity(500)->associatedtag(':alc:')->associatedpicto('r_alcool_#00')->commit();
        $container->add()->title('Alles unter 55% ist Wasser')->unlockquantity(600)->associatedtag(':alc:')->associatedpicto('r_alcool_#00')->commit();
        $container->add()->title('Dialyse')->unlockquantity(800)->associatedtag(':alc:')->associatedpicto('r_alcool_#00')->commit();
        $container->add()->title('Chef der Mauer')->unlockquantity(1)->associatedtag(':defwin:')->associatedpicto('r_defwin_#00')->commit();
        $container->add()->title('Schaufelführer')->unlockquantity(1)->associatedtag(':cdhwin:')->associatedpicto('r_cdhwin_#00')->commit();
        $container->add()->title('Ich bin ein Biest!')->unlockquantity(1)->associatedtag(':tamwin:')->associatedpicto('r_tamwin_#00')->commit();
        $container->add()->title('DdA Beste Buddler')->unlockquantity(1)->associatedtag(':scaddh:')->associatedpicto('r_scaddh_#00')->commit();
        $container->add()->title('Tarnexperte')->unlockquantity(1)->associatedtag(':rangwin:')->associatedpicto('r_rangwin_#00')->commit();
        $container->add()->title('Meisteringenieur')->unlockquantity(1)->associatedtag(':techwin:')->associatedpicto('r_techwin_#00')->commit();

        $data = $container->toArray();
    }
}