<?php

namespace MyHordes\Fixtures\Service;

use MyHordes\Plugins\Interfaces\FixtureProcessorInterface;

class CitizenStatusDataService implements FixtureProcessorInterface {

    public function process(array &$data): void
    {
        $data = array_replace_recursive($data, [
            'clean' => ['name' => 'clean',                                            'label' => 'Clean', 'description' => 'Du hast noch keine Drogen genommen.'],
            'hasdrunk' => ['name' => 'hasdrunk',                                         'label' => 'Getrunken', 'description' => 'Du hast heute bereits getrunken. Eine weitere Essensration erlaubt dir heute nicht weitere AP.'],
            'haseaten' => ['name' => 'haseaten',                                         'label' => 'Satt', 'description' => 'Du hast heute bereits gegessen. Eine weitere Essensration erlaubt dir heute nicht weitere AP.'],
            'camper' => ['name' => 'camper',                                           'label' => 'Umsichtiger Camper', 'description' => 'Du hast die letzte Nacht in der Kälte der Außenwelt verbracht. Dabei konntest du die Windrichtung und den Marsch der Zombiehorde beobachten. Damit bist du für den Rest des Tages in der Lage, erfolgreicher Gegenstände zu finden.'],
            'immune' => ['name' => 'immune',                                           'label' => 'Immunisiert', 'description' => 'Du hast Medizin eingenommen, die dich vor Infektionen schützt und dich davor bewahrt, zu einem Ghul zu werden.'],
            'hsurvive' => ['name' => 'hsurvive',                                         'label' => 'Den Tod besiegen', 'description' => 'Du hast deine Heldenfähigkeit "Den Tod besiegen" verwendet!'],
            'tired' => ['name' => 'tired',                                            'label' => 'Erschöpfung', 'description' => 'Du bist völlig erschöpft... Ruh dich aus oder iss etwas, um wieder zu Kräften zu kommen!'],
            'terror' => ['name' => 'terror',    'nw_def' => -30, 'nw_death' =>  0.45,  'label' => 'Angststarre', 'description' => 'Dir ist etwas furchtbares wiederfahren, und du bist vor Angst erstarrt! Du kannst dich nicht länger in einer von Zombies kontrollierten Zone aufhalten. Wenn du gefangen bist, kannst du nicht länger fliehen.'],
            'thirst1' => ['name' => 'thirst1',                                          'label' => 'Durst', 'description' => 'Du bist durstig... Das passiert immer dann wenn du am Vortag nichts getrunken hast oder wenn du in der Wüste lange Strecken gelaufen bist...'],
            'thirst2' => ['name' => 'thirst2',   'nw_def' => -10,                       'label' => 'Dehydriert', 'description' => 'Dein Durst hat ein kritisches Level erreicht! Trinke schnell etwas, oder du riskierst zu sterben!'],
            'drugged' => ['name' => 'drugged',   'nw_def' =>  10,                       'label' => 'Rauschzustand', 'description' => 'Du hast heute bereits Drogen konsumiert. Wenn du noch weitere Drogen nimmst, riskierst du eine Abhängigkeit!'],
            'addict' => ['name' => 'addict',    'nw_def' =>  15, 'nw_death' =>  0.10,  'label' => 'Drogenabhängig', 'description' => 'Du musst jeden Tag Drogen einnehmen! Wenn du eines morgens aufwachst, ohne am Tag zuvor Drogen genommen zu haben, wirst du sterben!'],
            'infection' => ['name' => 'infection', 'nw_def' => -15, 'nw_death' =>  0.20,  'label' => 'Infektion', 'description' => 'Eine furchtbare Krankheit brennt sich durch dein Innerstes... Vielleicht eine Art Infektion? Das beste, was du jetzt tun kannst, ist die richtige Medizin einzunehmen... Wenn du hingegen nichts tust, hast du eine 50/50 Chance, morgen tot aufzuwachen.'],
            'drunk' => ['name' => 'drunk',     'nw_def' =>  20, 'nw_death' => -0.04,  'label' => 'Trunkenheit', 'description' => 'Du stehst unter dem Einfluss von ziemlich starkem Alkohol... Du kannst vorerst keinen weiteren Alkohol zu dir nehmen.'],
            'hungover' => ['name' => 'hungover',  'nw_def' => -15, 'nw_death' =>  0.05,  'label' => 'Kater', 'description' => 'Du hast furchtbare Kopfschmerzen... Keinesfalls kannst du heute weiteren Alkohol zu dir nehmen.'],
            'wound1' => ['name' => 'wound1',    'nw_def' => -20, 'nw_death' =>  0.20,  'label' => 'Verwundung - Kopf', 'description' => 'Du bist am Kopf verletzt! Essen, trinken und Ausruhen wird dir 1AP weniger verschaffen.'],
            'wound2' => ['name' => 'wound2',    'nw_def' => -20, 'nw_death' =>  0.20,  'label' => 'Verwundung - Hände', 'description' => 'Du bist an der Hand verletzt! Essen, trinken und Ausruhen wird dir 1AP weniger verschaffen.'],
            'wound3' => ['name' => 'wound3',    'nw_def' => -20, 'nw_death' =>  0.20,  'label' => 'Verwundung - Arme', 'description' => 'Du bist an deinem Arm verletzt! Essen, trinken und Ausruhen wird dir 1AP weniger verschaffen.'],
            'wound4' => ['name' => 'wound4',    'nw_def' => -20, 'nw_death' =>  0.20,  'label' => 'Verwundung - Bein', 'description' => 'Du bist an deinen Beinen verletzt! Essen, trinken und Ausruhen wird dir 1AP weniger verschaffen.'],
            'wound5' => ['name' => 'wound5',    'nw_def' => -20, 'nw_death' =>  0.20,  'label' => 'Verwundung - Auge', 'description' => 'Du bist an den Augen verletzt! Essen, trinken und Ausruhen wird dir 1AP weniger verschaffen.'],
            'wound6' => ['name' => 'wound6',    'nw_def' => -20, 'nw_death' =>  0.20,  'label' => 'Verwundung - Fuß', 'description' => 'Du bist am Fuß verletzt! Essen, trinken und Ausruhen wird dir 1AP weniger verschaffen.'],
            'healed' => ['name' => 'healed',    'nw_def' => -10, 'nw_death' =>  0.10,  'label' => 'Bandagiert', 'description' => 'Du hast dich bereits von einer Verletzung erholt. Du kannst heute nicht erneut geheilt werden.'],

            'tg_dice' => ['name' => 'tg_dice' ],
            'tg_cards' => ['name' => 'tg_cards'],
            'tg_meta_wound' => ['name' => 'tg_meta_wound'],
            'tg_clothes' => ['name' => 'tg_clothes'],
            'tg_teddy' => ['name' => 'tg_teddy'],
            'tg_guitar' => ['name' => 'tg_guitar'],
            'tg_sbook' => ['name' => 'tg_sbook'],
            'tg_steal' => ['name' => 'tg_steal'],
            'tg_home_upgrade' => ['name' => 'tg_home_upgrade'],
            'tg_never' => ['name' => 'tg_never'],
            'tg_hero' => ['name' => 'tg_hero'],
            'tg_chk_forum' => ['name' => 'tg_chk_forum'],
            'tg_chk_active' => ['name' => 'tg_chk_active'],
            'tg_chk_workshop' => ['name' => 'tg_chk_workshop'],
            'tg_chk_build' => ['name' => 'tg_chk_build'],
            'tg_chk_movewb' => ['name' => 'tg_chk_movewb'],
            'tg_hide' => ['name' => 'tg_hide'],
            'tg_tomb' => ['name' => 'tg_tomb'],
            'tg_home_clean' => ['name' => 'tg_home_clean'],
            'tg_home_shower' => ['name' => 'tg_home_shower'],
            'tg_home_heal_1' => ['name' => 'tg_home_heal_1'],
            'tg_home_heal_2' => ['name' => 'tg_home_heal_2'],
            'tg_home_defbuff' => ['name' => 'tg_home_defbuff'],
            'tg_rested' => ['name' => 'tg_rested' ],
            'tg_shaman_immune' => ['name' => 'tg_shaman_immune' ],
            'tg_shaman_heal' => ['name' => 'tg_shaman_heal' ],
            'tg_ghoul_eat' => ['name' => 'tg_ghoul_eat' ],
            'tg_no_hangover' => ['name' => 'tg_no_hangover' ],
            'tg_ghoul_corpse' => ['name' => 'tg_ghoul_corpse' ],
            'tg_betadrug' => ['name' => 'tg_betadrug' ],
            'tg_build_vote' => ['name' => 'tg_build_vote' ],
            'tg_meta_winfect' => ['name' => 'tg_meta_winfect' ],
            'tg_infect_wtns' => ['name' => 'tg_infect_wtns' ],
            'tg_insurrection' => ['name' => 'tg_insurrection'],
            'tg_got_xmas_gift' => ['name' => 'tg_got_xmas_gift'],
            'tg_april_ooze' => ['name' => 'tg_april_ooze'],
            'tg_paranoid' => ['name' => 'tg_paranoid'],
            'tg_novlamps' => ['name' => 'tg_novlamps'],
            'tg_air_ghoul' => ['name' => 'tg_air_ghoul'],
            'tg_air_infected' => ['name' => 'tg_air_infected'],
            'tg_tried_pp' => ['name' => 'tg_tried_pp'],
            'tg_meta_ginfect' => ['name' => 'tg_meta_ginfect'],
            'tg_spirit_guide' => ['name' => 'tg_spirit_guide'],
            'tg_revolutionist' => ['name' => 'tg_revolutionist'],
            'tg_stats_locked' => ['name' => 'tg_stats_locked'],
            'tg_rec_heroic' => ['name' => 'tg_rec_heroic'],
            'tg_unban_altar' => ['name' => 'tg_unban_altar'],
        ]);
    }
}